default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Shubham@123
  host: localhost
  port: 5432

development:
  <<: *default
  database: shubham_dev

test:
  <<: *default
  database: shubham_test

production:
  <<: *default
  database: shubham_prod